import assets from "./assets";

export const foodData = [
    {
        id: "F01",
        name: "Zinger Sandwich",
        brandId: "B01",
        image: assets.food01,
        price: 18.5,
        distance: "2km",
        time: "15min",
        starRatings: 4.9,
        totalRatings: 783,
        trending: true,
        promotion: false,
    },
    {
        id: "F02",
        name: "Hot Wings",
        brandId: "B01",
        image: assets.food02,
        price: 25.0,
        distance: "2km",
        time: "20min",
        starRatings: 4.7,
        totalRatings: 813,
        trending: false,
        promotion: true,
    },
    {
        id: "F03",
        name: "Big Mac",
        brandId: "B02",
        image: assets.food03,
        price: 32.0,
        distance: "8km",
        time: "25min",
        starRatings: 4.9,
        totalRatings: 1059,
        trending: true,
        promotion: false,
    },
    {
        id: "F04",
        name: "Grand Chicken",
        brandId: "B02",
        image: assets.food04,
        price: 28.0,
        distance: "8km",
        time: "25min",
        starRatings: 4.3,
        totalRatings: 515,
        trending: true,
        promotion: true,
    },
    {
        id: "F05",
        name: "Hot White Chocolate Mocha",
        brandId: "B03",
        image: assets.food05,
        price: 17.0,
        distance: "5km",
        time: "30min",
        starRatings: 4.9,
        totalRatings: 695,
        trending: true,
        promotion: false,
    },
    {
        id: "F06",
        name: "Iced White Chocolate Mocha",
        brandId: "B03",
        image: assets.food06,
        price: 17.0,
        distance: "5km",
        time: "30min",
        starRatings: 4.9,
        totalRatings: 564,
        trending: false,
        promotion: false,
    },
    {
        id: "F07",
        name: "Iced Caffè Latte",
        brandId: "B03",
        image: assets.food07,
        price: 22.75,
        distance: "5km",
        time: "40min",
        starRatings: 4.5,
        totalRatings: 887,
        trending: false,
        promotion: true,
    },
    {
        id: "F08",
        name: "Chicken BBQ",
        brandId: "B05",
        image: assets.food08,
        price: 26.3,
        distance: "12km",
        time: "45min",
        starRatings: 4.5,
        totalRatings: 1007,
        trending: true,
        promotion: false,
    },
    {
        id: "F09",
        name: "Classic Pepperoni",
        brandId: "B05",
        image: assets.food09,
        price: 25.75,
        distance: "12km",
        time: "45min",
        starRatings: 4.1,
        totalRatings: 211,
        trending: false,
        promotion: true,
    },
    {
        id: "F10",
        name: "Mighty Zinger Sandwich",
        brandId: "B01",
        image: assets.food10,
        price: 21,
        distance: "2km",
        time: "20min",
        starRatings: 4.8,
        totalRatings: 133,
        trending: true,
        promotion: true,
    },
    {
        id: "F11",
        name: "Flat White",
        brandId: "B08",
        image: assets.food11,
        price: 15,
        distance: "14km",
        time: "25min",
        starRatings: 4.6,
        totalRatings: 456,
        trending: true,
        promotion: true,
    },
    {
        id: "F12",
        name: "Mocha",
        brandId: "B08",
        image: assets.food12,
        price: 17,
        distance: "14km",
        time: "25min",
        starRatings: 4.9,
        totalRatings: 389,
        trending: true,
        promotion: false,
    },
];

export const BrandsData = [
    {
        id: "B01",
        name: "KFC",
        image: assets.brand01,
    },
    {
        id: "B02",
        name: "McDonald's",
        image: assets.brand02,
    },
    {
        id: "B03",
        name: "Starbucks",
        image: assets.brand03,
    },
    {
        id: "B04",
        name: "Subway",
        image: assets.brand04,
    },
    {
        id: "B05",
        name: "Pizza Hut",
        image: assets.brand05,
    },
    {
        id: "B06",
        name: "Burger King",
        image: assets.brand06,
    },
    {
        id: "B07",
        name: "Papa John's",
        image: assets.brand07,
    },
    {
        id: "B08",
        name: "Costa",
        image: assets.brand08,
    },
];
